### ISSUE TITLE
Set-MpPreference -EnableControlledFolderAccess Enabled

### ISSUE THREAD

**Issue by eyaladmin** [simeononsecurity/Windows-Defender-Hardening#1]
Hi 

about #Enable Controlled Folder Access and setting to block mode
the script currently has an error, as it trying to enable Controlled Folder with $ture and not with "enable"

Thanks

**Comment by simeononsecurity** [comment]
> Hi 
> 
> about #Enable Controlled Folder Access and setting to block mode
> the script currently has an error, as it trying to enable Controlled Folder with $ture and not with "enable"
> 
> Thanks

You're correct. We see that in the documentation now. Thanks!


https://docs.microsoft.com/en-us/powershell/module/defender/set-mppreference?view=windowsserver2022-ps
