### ISSUE TITLE
Non standard elevation mechanism

### ISSUE THREAD

**Issue by Harvester57** [simeononsecurity/Windows-Defender-Hardening#2]
**Describe the bug**
The elevation mechanism used (`Elevate-Privileges SeTakeOwnershipPrivilege`) is non standard, depend on the external module `take-own.psm1`, and is not compatible with Constrained Language Mode.

**To Reproduce**
1. Launch the script

**Proposed solution**
Use a generic elevation mechanism (such as RunAs):

```
$grp = [int](whoami /GROUPS | ForEach-Object { if ($_ -match '(.*)S-1-16-(.*)') { $matches[2] } } )
if (-Not ($grp -eq 12288)) {
  $list = "& $($myInvocation.MyCommand.Source) "
  $PSBoundParameters.Keys | ForEach-Object { $list += "-$($_)" }
  Start-Process powershell.exe -Verb RunAs -ArgumentList $list
  exit 0
}
```

**Comment by simeononsecurity** [comment]
Unfortunately the runas mechanism doesn't work in harden environments either.  If you use our other scripts, it will disable runas functionality.
We appreciate the notification. However our suggestion is to comment out those lines if you're working in constrained language mode.
