### ISSUE TITLE
Uninstall feature

### ISSUE THREAD

**Issue by xkpx64** [simeononsecurity/Windows-Defender-Hardening#3]
Is it possible to have uninstall/removal param or additional script to the package.
Thnaks

**Comment by simeononsecurity** [comment]
While that would be nice to have, The script is just not set up in a way where that is possible.
We do not ever intend for these to be run by every day users. You should be capable of reviewing the script and what it does before running it. At the very least test it in a virtual machine before running it on any machine that is actually used.
If you have a problem, or something broke, we can try our best to help you. However, a roll back feature is just not on the books for the time being.
